### ISSUE TITLE
New Company Footer

### ISSUE THREAD

**Issue by piet3r** [ProfessorFrancken/ProfessorFrancken#69]
It might be a good idea to make the Company Footer a bit more dynamic.

# Right now
The Company Footer is quite static right now. If you make shrink your windows (or watch the website on mobile phone) the company's will stack:
![footerweb](https://cloud.githubusercontent.com/assets/23217890/19937929/59841e16-a123-11e6-825c-c0170f24cd37.png)

This costs a lot of space. Especially on mobile phone

# Improvements
-Make the lofo smaller smaller

-When the logo's don't fit on the page; Put all logo's in a automatic scrolling bar. 
![scrolling_gif](https://cloud.githubusercontent.com/assets/23217890/19938977/444b6de8-a127-11e6-8c13-5be1c1e289da.gif)
Note: It should not be scrolling if all Logo's fit on screen

**Comment by MarkRedeman** [comment]
The logos should definitely be smaller (especially on mobile).

Currently these logos are hardcoded [`sponsors.blade.php`](https://github.com/ProfessorFrancken/ProfessorFrancken/blob/master/src/Infrastructure/Http/Views/layout/_sponsors.blade.php) though at some point these should be configurable from a admin page (which should also have an option to upload a logo).

Perhaps instead of always showing all logos we could only show 5 randomly selected logos?

A drawback of having a scrollbar for the logos would be that only a small subset of the logos are shown at a time and it could be distracting if the logos move automatically.

**Comment by piet3r** [comment]
Hey Mark,

Company's pay for the hyperlink at the buttom of the page. So it wouldn't be very nice if not all logo's are shown.

Another solution could be: Automatic adjusting logo sizes?

**Comment by MarkRedeman** [comment]
Changing the size of the logo is probably the best / simplest solution.

I can see two more options:
- We could add an option where companies pay for the percentage of time that their logo is viewed. Though this isn't complicated to implement technically it probably is hard to sell, so we would have to discuss with the rest of the external relations committee.
- On mobile devices instead of showing logo's only show the company's name with a link to their webpage.

Once we've set up the company profile admin pages I want to add an opt in option whether a company's logo should be showed in the footer. So that only the companies that pay for it will be showed in the footer.

**Comment by piet3r** [comment]
Can be closed (?)
Not a real issue. In the future the logo's can be scaled to smaller sizes.
